<a href="https://colab.research.google.com/github/poonamks/Demo/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import time
print(time.ctime())

Sat Dec 16 01:34:22 2023


In [1]:
import numpy as np

In [2]:
np.ones(8)*8

array([8., 8., 8., 8., 8., 8., 8., 8.])

In [4]:
arr = np.arange(26,51).reshape(5,5)
arr


array([[26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [5]:
arr[2:,1:]

array([[37, 38, 39, 40],
       [42, 43, 44, 45],
       [47, 48, 49, 50]])

In [8]:
arr[3:,2][0]

43

In [9]:
arr[0:3,1:2]

array([[27],
       [32],
       [37]])

In [10]:
arr[-1]

array([46, 47, 48, 49, 50])

In [11]:
arr[4]

array([46, 47, 48, 49, 50])

In [12]:
arr = np.arange(10,40).reshape(6,5)
arr

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [13]:
np.sum(arr)

735

In [14]:
np.std(arr)

8.65544144839919

In [15]:
np.mean(arr)

24.5